title: SciTech
email: your-email@example.com
description: >-
  A space where science meets beauty. Exploring the neurobiology 
  of wellness and the tech behind the glow.
baseurl: "" 
url: "https://alessacsardi.github.io"

# Color Palette (Relaxing Aura)
colors:
  beige: "#f4efe6"
  emerald: "#0b3d2e"
  gold: "#D5B038"
  text: "#2b2b2b"

theme: minima # A lightweight base to build your custom styles on
plugins:
  - jekyll-feed
