title: SciTech
description: The Neurobiology of Gorgeous.
baseurl: "/SciTech"
url: "https://alessacsardi.github.io"

# Fixed Color Keys
colors:
  cream: "#f4efe6"
  emerald: "#0b3d2e"
  gold: "#D5B038"
  black: "#000000"
  text: "#1a1a1a"

theme: # Keep this blank
