title: SciTech
description: A space where science meets beauty.

# SYNC SETTINGS: Vital for /SciTech/
baseurl: "/SciTech"
url: "https://alessacsardi.github.io"

# Relaxing Aura Palette
colors:
  beige: "#f4efe6"
  emerald: "#0b3d2e"
  gold: "#D5B038"
  text: "#2b2b2b"

# DELETE the 'theme: none' line. If you want no theme, just leave it empty like this:
theme:
